name: openiothub_common_pages
description: openiothub_common_pages
version: 1.0.5+83
homepage: https://github.com/OpenIoTHub
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.19.0 <= 1.0.0'

  # OpenIoTHub 内部包
  openiothub_constants: ^1.0.0
  openiothub_api: ^1.0.2+1
  openiothub_grpc_api: ^1.0.2+1
  openiothub_ads: ^0.0.1

  # 网络与通信
  url_launcher: ^6.1.11
  webview_flutter: ^4.8.0
  flutter_inappwebview: ^6.1.5
  dio: ^5.5.0+1
  bonsoir: ^5.1.11

  # 数据存储
  shared_preferences: ^2.1.1

  # 状态管理
  provider: ^6.0.2

  # UI 组件
  tdesign_flutter: ^0.2.3
  oktoast: ^3.3.2+1
  qr_flutter: ^4.1.0
  package_info_plus: ^8.0.0
  image: ^4.0.9

  # WiFi 配网
  airkiss_dart: ^1.0.0
  network_info_plus: ^6.1.1

  # 平台功能
  permission_handler: ^11.3.1
  wakelock_plus: ^1.3.2
  sign_in_with_apple: ^7.0.1

  # 第三方登录
  wechat_kit: ^6.0.1


dev_dependencies:
  intl_utils: ^2.8.3
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

flutter_gen:
  assets:
    - lib/l10n/*.arb

flutter:
  uses-material-design: true
  generate: true
  assets:
   - assets/images/
   - assets/images/feedback/