include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/generated/**"
    - "lib/generated/**"

linter:
  rules:
    # 错误预防
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true

    # 风格一致性
    always_declare_return_types: true
    avoid_catches_without_on_clauses: false
    avoid_returning_this: true
    cascade_invocations: false
    directives_ordering: true
    omit_local_variable_types: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_lambdas: true
    use_string_buffers: true

    # 可读性
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
