name: openiothub_workspace

packages:
  - .
  - packages/openiothub_mobile_service

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    description: Run static analysis
    run: dart analyze --fatal-infos

  format:
    description: Format all Dart files
    run: dart format .

  clean:
    description: Clean all packages
    run: flutter clean
    exec:
      concurrency: 1

  get:
    description: Get dependencies for all packages
    run: flutter pub get
    exec:
      concurrency: 3

  l10n:
    description: Generate localizations
    run: flutter gen-l10n

  test:
    description: Run tests
    run: flutter test
    packageFilters:
      dirExists:
        - test
sdkPath: .fvm/flutter_sdk
