name: openiothub
version: 0.1.1
summary: OpenIoTHub App
description: OpenIoTHub App for IoT device and proxy!

confinement: strict
base: core22
grade: stable

#slots:
#  dbus-openiothub: # adjust accordingly to your app name
#    interface: dbus
#    bus: session
#    name: org.bar.super_cool_app # adjust accordingly to your app name and

apps:
  openiothub:
    command: openiothub
    extensions: [gnome]
    plugs:
      - network
      - network-bind
#    slots:
#      - dbus-openiothub
parts:
  openiothub:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
