name: openiothub_ads
description: "OpenIoTHub ADs"
version: 0.0.1
homepage: https://github.com/OpenIoTHub
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # OpenIoTHub 内部包
  openiothub_constants: ^1.0.2+3

  # 广告 SDK
  gtads: ^1.5.0
  gtads_ylh: ^1.5.0
  google_mobile_ads: ^6.0.0

  # 数据存储
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
